DROP TABLE MOVIE;
CREATE TABLE MOVIE
(
    MOVIE_NO NUMBER PRIMARY KEY,
    MOVIE_TITLE VARCHAR2(400 BYTE),
    MOVIE_GENRE VARCHAR2(400 BYTE),
    MOVIE_INFO VARCHAR2(400 BYTE),
    MOVIE_OPEN_DT DATE
);

-- 시퀀스
DROP SEQUENCE MOVIE_SEQ;
CREATE SEQUENCE MOVIE_SEQ NOCACHE;